// draft is generated by Gemini
#include <iostream>
#include <vector>
#include <numeric>
#include <random>
#include <algorithm>
#include <cmath>
#include <set>
#include <map>

#include "DSU_uint8.hpp"
#include "CircuitGenerator.hpp"

#define DEBUG 1

// define a macro to run function only in debug mode
#define DEBUG_RUN(func) do { if (DEBUG) { func; } } while(0)

void debug_print(const std::string& msg) {
    if (DEBUG) {
        std::cout << msg << std::endl;
    }
}

bool test_circuit(uint8_t N, uint8_t M, uint8_t V, const std::vector<uint8_t>* pool_ptr, const std::vector<uint8_t>* parents_ptr, const CircuitGenerator::sp2v_t* switch_p2pos_ptr) {
    for (int bitmask = 0; bitmask < (1 << N); ++bitmask) {
        std::cout << "Simulating switch configuration: " << std::bitset<16>(bitmask).to_string().substr(16 - N) << std::endl;
        // Here you would implement the logic to simulate the circuit based on the current switch configuration (bitmask)
        // You can use the pool_ptr to get the pin information, parents_ptr for connectivity, and switch_p2pos_ptr for quick lookup of switch pin positions.
        DSU_uint8 dsu (std::vector<uint8_t>{*parents_ptr}); // initialize DSU with the parent array from the generator
        for(int i = 0; i < N; ++i) {
            dsu.unite((*switch_p2pos_ptr)[COM][i], (bitmask >> i) & 1 == 0 ? (*switch_p2pos_ptr)[POS][i] : (*switch_p2pos_ptr)[NEG][i]);
        }

        CircuitGenerator::v2p_t v2p {};
        std::array<int, 0xFF> root2vertex;//if the root is seen, map it to a vertex index, otherwise assign a new vertex index
        std::fill(root2vertex.begin(), root2vertex.end(), -1);
        // parse the pool based on DSU to v2p_t for graph search
        int n_sets = 0;
        for (int i = 0; i < pool_ptr->size(); ++i) {
            if ((*pool_ptr)[i] >> 6 == SWITCH) continue;
            uint8_t root = dsu.find(i);
            if (root2vertex[root] == -1) {
                root2vertex[root] = ++n_sets;
            }
            v2p[root2vertex[root]].second[v2p[root2vertex[root]].first++] = (*pool_ptr)[i];
        }
        CircuitGenerator::print_v2p(v2p);
        // find vertices with p+ and p-
        int vertex_with_p_plus = -1, vertex_with_p_neg = -1;
        for(int i = 0; i < v2p.size(); ++i) {
            bool has_p_plus = false, has_p_neg = false;
            for (int j = 0; j < v2p[i].first; ++j) {
                if ((v2p[i].second[j] >> 6) == POWER) {
                    if ((v2p[i].second[j] & 0x3F) == 0) vertex_with_p_plus = i;
                    else vertex_with_p_neg = i;
                }
            }
        }
        if (vertex_with_p_plus == vertex_with_p_neg) {
            std::cout << "Invalid circuit: power rails are shorted!" << std::endl;
            return false; // regenerate circuit
        }
        std::vector<int8_t> led_states(M, -1);// -1 means unknown, 0 means off, 1 means on

        // Simplify the circuit before search
        // 1. search entire v2p, and find LEDs whose positive and negative pins are in the same vertex, which means they will never light up, set their states and remove them from v2p
        // before 2, build lp2v for quick lookup of LED's positive and negative pin vertex index
        // 2. search vertices with power pins, if a vertex have positive power pin and negative led pin, then the led is reverse biased and will never light up, set their states and remove them from v2p; 
        //     if a vertex have negative power pin and positive led pin, then the led is also reverse biased and will never light up, set their states and remove them from v2p
        // 3. if a LED's positive pin is in the power+ vertex and negative pin is in the power- vertex, then the LED is always on, set their states and remove them from v2p
        // start search
        // start from power+ vertex, do a DFS to find all reachable vertices, if we can reach the power- vertex, then the circuit is invalid (leds are light up, but are dim)
        // otherwise, all the leds are off, the circuit is valid
    }
    return true;
}


int main() {
    uint8_t N = 5; // Switches
    uint8_t M = 9; // LEDs
    uint8_t V = 7; // Vertex junction points
    CircuitGenerator generator(N, M, V);
    for (int i = 0; i < 1; ++i) {
        std::cout << "Generating circuit configuration " << i + 1 << "..." << std::endl;
        auto [pool_ptr, parents_ptr, switch_p2pos_ptr] = generator.generate();
        generator.print_current_configuration();

        
    }

    return 0;
}
