// draft is generated by Gemini
#include <iostream>
#include <vector>
#include <thread>
#include <atomic>
#include <mutex>
#include <climits>

#include "SwitchBlackbox.hpp"

struct opt_t {
    int num_workers = -1;
    int target_count = 1000;

    uint8_t N = 5; // Switches
    uint8_t M = 8; // Outputs
    uint8_t V = 15; // Vertices
} opt;

struct SharedState {
    std::atomic<int> cnt{0};
    std::mutex mtx;
    uint32_t max_dist_adj = 0;
    uint32_t max_dist_2 = 0;
    int min_stdev = INT_MAX;
    int max_n1s = 0;
    int min_n1s = INT_MAX;
    std::string s_max_dist_adj;
    std::string s_max_dist_2;
    std::string s_min_stdev;
    std::string s_max_n1s;
    std::string s_min_n1s;
};

void worker(const opt_t& opt, SharedState& shared, int id) {
    SwitchBlackbox sbb(opt.N, opt.M, opt.V);
    const int full_unique = 1 << opt.N;

    while (shared.cnt.fetch_add(1, std::memory_order_relaxed) < opt.target_count) {
        SwitchBlackbox::Statistics s;
        do {
            sbb.generate();
        } while(!sbb.filter());
        std::lock_guard<std::mutex> lock(shared.mtx);
        std::vector<size_t> fc = sbb.fc;
        std::cout << "Core id:" << id << std::endl;
        std::cout << "fc: " << fc[0] << " " << fc[1] << " " << fc[2] << " " << fc[3] << " " << fc[4] << " " << std::endl;
        s = sbb.find_best();
    }
}

int main() {
    SharedState shared;
    std::vector<std::thread> threads;
    // unsigned int cores = 1;
    unsigned int cores = std::thread::hardware_concurrency();
    std::cout << "#cores: " << cores << std::endl;
    if (cores == 1) {
        //debug mode:
        std::cout << "debug mode" << std::endl;
        worker(opt, shared, 0);
        return 0;
    }
    
    opt.num_workers = cores - 1;
    threads.reserve(opt.num_workers);

    for (int i = 0; i < opt.num_workers; ++i) {
        threads.emplace_back(worker, std::cref(opt), std::ref(shared), i);
    }
    for (auto& t : threads) {
        t.join();
    }
    
    // SwitchBlackbox sbb(opt.N, opt.M, opt.V);
    // sbb.verbose = 1;

    // std::cout << std::endl << "Max Distance " << std::endl;
    // sbb.generate(shared.s_max_dist_adj);
    // sbb.basic_stats();
    
    // std::cout << std::endl << "Max Distance 2" << std::endl;
    // sbb.generate(shared.s_max_dist_2);
    // sbb.basic_stats();
    
    // std::cout << std::endl << "Min StDev" << std::endl;
    // sbb.generate(shared.s_min_stdev);
    // sbb.basic_stats();
    
    // std::cout << std::endl << "Max N of bit1" << std::endl;
    // sbb.generate(shared.s_max_n1s);
    // sbb.basic_stats();
    
    // std::cout << std::endl << "Min N of bit1" << std::endl;
    // sbb.generate(shared.s_min_n1s);
    // sbb.basic_stats();

    return 0;
}
