// draft is generated by Gemini
#include <iostream>
#include <vector>
#include <numeric>
#include <random>
#include <algorithm>
#include <cmath>
#include <set>
#include <map>
#include <string>
#include <array>
#include <functional>

#include "DSU_uint8.hpp"
#include "CircuitGenerator.hpp"

#define DEBUG 1

// define a macro to run function only in debug mode
#define DEBUG_RUN(func) do { if (DEBUG) { func; } } while(0)

void debug_print(const std::string& msg) {
    if (DEBUG) {
        std::cout << msg << std::endl;
    }
}

bool test_circuit(uint8_t N, uint8_t M, const std::vector<uint8_t>* pool_ptr, const std::vector<uint8_t>& parents, const CircuitGenerator::sp2v_t* switch_p2pos_ptr) {
    for (int bitmask = 0; bitmask < (1 << N); ++bitmask) {
        std::cout << "bitmask " << std::bitset<16>(bitmask).to_string().substr(16 - N) << ", ";
        printf("x");
        // Here you would implement the logic to simulate the circuit based on the current switch configuration (bitmask)
        // You can use the pool_ptr to get the pin information, parents for connectivity, and switch_p2pos_ptr for quick lookup of switch pin positions.
        DSU_uint8 dsu(parents); // initialize DSU with the parent array from the generator
        
        printf("z");
        for(int i = 0; i < N; ++i) {
            dsu.unite((*switch_p2pos_ptr)[COM][i], ((bitmask >> i) & 1) == 0 ? (*switch_p2pos_ptr)[POS][i] : (*switch_p2pos_ptr)[NEG][i]);
        }
        printf("a");

        CircuitGenerator::v2p_t v2p {};
        std::array<int, 0xFF> root2vertex;//if the root is seen, map it to a vertex index, otherwise assign a new vertex index
        std::fill(root2vertex.begin(), root2vertex.end(), -1);
        // parse the pool based on DSU to v2p_t for graph search
        int n_sets = 0;
        for (int i = 0; i < pool_ptr->size(); ++i) {
            if ((*pool_ptr)[i] >> 6 == SWITCH) continue;
            uint8_t root = dsu.find(i);
            if (root2vertex[root] == -1) {
                root2vertex[root] = ++n_sets;
            }
            v2p[root2vertex[root]].second[v2p[root2vertex[root]].first++] = (*pool_ptr)[i];
        }
        printf("b");

        // find vertices with p+ and p-
        int vertex_with_p_plus = -1, vertex_with_p_neg = -1;
        for(int i = 0; i < v2p.size(); ++i) {
            for (int j = 0; j < v2p[i].first; ++j) {
                if ((v2p[i].second[j] >> 6) == POWER) {
                    if ((v2p[i].second[j] & 0x3F) == 0) vertex_with_p_plus = i;
                    else vertex_with_p_neg = i;
                }
            }
        }
        printf("c");
        
        if (vertex_with_p_plus == vertex_with_p_neg) {
            std::cout << "Invalid circuit: power rails are shorted!" << std::endl;
            return false; // regenerate circuit
        }
        // std::cout << CircuitGenerator::get_vp2_oneline_string(v2p) << std::endl;
        std::vector<int8_t> led_states(M, -1); // -1 means unknown, 0 means off, 1 means on, 2 means dim (optional, may not be used)

        CircuitGenerator::lp2v_t lp2v;
        lp2v[POS].fill(0xFF);
        lp2v[NEG].fill(0xFF);

        // 1. Build lp2v to map LED pin types to vertices and mark LEDs whose pins are in the same vertex.
        for (size_t v = 0; v < v2p.size(); ++v) {
            for (int j = 0; j < v2p[v].first; ++j) {
                uint8_t pin = v2p[v].second[j];
                if ((pin >> 6) != LED) continue;
                uint8_t pin_type = (pin >> 4) & 0x3;
                uint8_t led_idx = pin & 0xF;
                lp2v[pin_type][led_idx] = static_cast<uint8_t>(v);
            }
        }
        for (uint8_t led_idx = 0; led_idx < M; ++led_idx) {
            if (lp2v[POS][led_idx] != 0xFF && lp2v[POS][led_idx] == lp2v[NEG][led_idx]) {
                led_states[led_idx] = 0; // this LED is definitely off because both pins are in the same vertex, we can mark it as not copy for later simplification
            }
        }

        // 2. Search vertices with power pins and mark reverse-biased LEDs.
        for (size_t i = 0; i < v2p[vertex_with_p_plus].first; ++i) {
            uint8_t pin = v2p[vertex_with_p_plus].second[i];
            if ((pin >> 6) != LED || ((pin >> 4) & 0x3) == POS) continue;
            uint8_t led_idx = pin & 0xF; // this is a negative pin of an LED connected to p+, it is reverse biased, so it must be off
            if (led_states[led_idx] == -1) {
                led_states[led_idx] = 0; 
            }
        }
        for (size_t i = 0; i < v2p[vertex_with_p_neg].first; ++i) {
            uint8_t pin = v2p[vertex_with_p_neg].second[i];
            if ((pin >> 6) != LED || ((pin >> 4) & 0x3) == NEG) continue;
            uint8_t led_idx = pin & 0xF; // this is a positive pin of an LED connected to p-, it is reverse biased, so it must be off
            if (led_states[led_idx] == -1) {
                led_states[led_idx] = 0; 
            }
        }

        // 3. Mark LEDs that are definitely on when + is in p+ vertex and - is in p- vertex.
        for (uint8_t i = 0; i < M; ++i) {
            if (lp2v[POS][i] == vertex_with_p_plus && lp2v[NEG][i] == vertex_with_p_neg) {
                assert(led_states[i] == -1); // check conflict
                led_states[i] = 1;
            }
        }

        // 4. simplify v2p
        for (int i = 0; i < v2p.size(); ++i) {
            int write_ptr = 0;
            for (int j = 0; j < v2p[i].first; ++j) {
                uint8_t pin = v2p[i].second[j];
                if ((pin >> 6) == LED) {
                    uint8_t led_idx = pin & 0xF;
                    if (led_states[led_idx] != -1) continue; // skip definitely off LEDs
                }
                v2p[i].second[write_ptr++] = pin;
            }
            v2p[i].first = write_ptr;
        }

        std:: cout << "\tLED states: ";
        for (int i = 0; i < M; ++i) {
            std::cout << ((led_states[i] == -1) ? "?" : (led_states[i] == 0) ? "0" : "1");
        }

        std::cout << ". Simplified v2p: " << CircuitGenerator::get_vp2_oneline_string(v2p) << std::endl;

        // start DFS from power+ vertex, do a DFS to find all reachable vertices by following the LED's + pin to - pin from the current vertex to the next vertex. 
        // The switch states have been applied, so the current v2p only has power and LED, and switch has been simplified out. We can just follow the LED connections without worrying about switch states. 
        // If we can reach the power- vertex, then this circuit is *invalid* because it means multiple LEDs are in series and are dim. 
        std::set<int> visited;
        std::function<bool(int)> dfs = [&](int v) -> bool {
            visited.insert(v);
            for (int j = 0; j < v2p[v].first; ++j) {
                uint8_t pin = v2p[v].second[j];
                if ((pin >> 6) == POWER) {
                    if ((pin & 0x3F) == 0) continue; // skip power+
                    return true; // reached power- through LED chain
                }
                // only follow positive LED pins
                if (((pin >> 4) & 0x3) == NEG) continue;
                uint8_t led_idx = pin & 0xF;
                int next_vertex = static_cast<int>(lp2v[NEG][led_idx]);
                // lp2v uses 0xFF as "not found" sentinel
                if (visited.count(next_vertex)) continue;
                if (dfs(next_vertex)) return true;
            }
            return false;
        };
        if (!dfs(vertex_with_p_plus)) {
            // std::cout << "Circuit is invalid." << std::endl;
            return false;
        }
    }
    return true;
}


int main() {
    uint8_t N = 5; // Switches
    uint8_t M = 9; // LEDs
    const std::vector<uint8_t> vertex_sizes = {2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4 ,5}; // Number of pins in each vertex (must sum to pool size and satisfy minimum distance constraint)
    assert(std::accumulate(vertex_sizes.begin(), vertex_sizes.end(), 0) == 2 + 2 * M + 3 * N); // Ensure vertex sizes sum to total pin count
    CircuitGenerator generator(N, M, vertex_sizes);
    const std::vector<uint8_t> parents = generator.get_parents();
    for (int i = 0; i < 100; ++i) {
        std::cout << "Generating circuit configuration " << i + 1 << "..." << std::endl;
        auto [pool_ptr, switch_p2pos_ptr] = generator.generate();
        // generator.print_current_configuration();
        std::cout << CircuitGenerator::get_vp2_oneline_string(generator.get_v2p()) << std::endl;
        // std::cout << "Simulating switch configuration" << std::endl;
        if (test_circuit(N, M, pool_ptr, parents, switch_p2pos_ptr)) {
            std::cout << "Circuit is valid!" << std::endl;
            break;
        }
        
    }

    return 0;
}
