// draft is generated by Gemini
#include <iostream>
#include <vector>
#include <thread>
#include <atomic>
#include <mutex>
#include <climits>

#include "SwitchBlackbox.hpp"

struct opt_t {
    int num_workers = 4;
    int target_count = 20000;

    uint8_t N = 5; // Switches
    uint8_t M = 8; // Outputs
    uint8_t V = 15; // Vertices
} opt;

struct SharedState {
    std::atomic<int> cnt{0};
    std::mutex mtx;
    uint32_t max_dist_adj = 0;
    uint32_t max_dist_2 = 0;
    int min_stdev = INT_MAX;
    int max_n1s = 0;
};

void worker(const opt_t& opt, SharedState& shared) {
    SwitchBlackbox sbb(opt.N, opt.M, opt.V);
    const int full_unique = 1 << opt.N;

    while (shared.cnt.load(std::memory_order_relaxed) < opt.target_count) {
        SwitchBlackbox::Statistics s;
        do {
            sbb.generate();
            s = sbb.basic_stats();
        } while (s.max_reachable_n < opt.M);

        if (sbb.best_choice_of_m_vertices() != full_unique) {
            continue;
        }

        auto dist_1 = sbb.sum_reachable_distance_for_adjacent_bitmasks(1, opt.V);
        auto dist_2 = sbb.sum_reachable_distance_for_adjacent_bitmasks(2, opt.V);
        auto n1s = sbb.n_1s();
        auto stdev = sbb.stdev();

        std::lock_guard<std::mutex> lock(shared.mtx);
        if (shared.cnt >= opt.target_count) {
            break;
        }

        bool good = false;
        if (dist_2 > shared.max_dist_2) {
            good = true;
            shared.max_dist_2 = dist_2;
        }
        if (dist_1 > shared.max_dist_adj) {
            good = true;
            shared.max_dist_adj = dist_1;
        }
        if (n1s > shared.max_n1s) {
            good = true;
            shared.max_n1s = n1s;
        }
        if (stdev < shared.min_stdev || stdev == 0) {
            good = true;
            shared.min_stdev = stdev;
        }

        if (good) {
            std::string config = sbb.get_readable_config();
            std::cout << "Unique config: " << full_unique << ", config: " << config;
            std::cout << "distance 1: " << dist_1 << ", distance 2: " << dist_2
                      << ", n1s:" << n1s << ", stdev: " << stdev << std::endl;

            sbb.generate(sbb.get_readable_config());
            if (config != sbb.get_readable_config()) {
                std::cerr << "error!" << std::endl;
            }
        }

        ++shared.cnt;
    }
}

int main() {
    SharedState shared;
    std::vector<std::thread> threads;
    threads.reserve(opt.num_workers);

    for (int i = 0; i < opt.num_workers; ++i) {
        threads.emplace_back(worker, std::cref(opt), std::ref(shared));
    }
    for (auto& t : threads) {
        t.join();
    }

    return 0;
}
