// draft is generated by Gemini
#include <iostream>
#include <vector>
#include <numeric>
#include <random>
#include <algorithm>
#include <cmath>
#include <set>
#include <map>
#include <string>
#include <array>
#include <functional>
#include <iostream>
#include <fstream>
#include <thread>
#include <atomic>
#include <chrono>

#include "DSU_uint8.hpp"
#include "SwitchBlackbox.hpp"
#include "ThreadSafeQueue.hpp"

#define DEBUG 1

// define a macro to run function only in debug mode
#define DEBUG_RUN(func) do { if (DEBUG) { func; } } while(0)

void debug_print(const std::string& msg) {
    if (DEBUG) {
        std::cout << msg << std::endl;
    }
}

using data_t = std::tuple<std::vector<uint8_t>, std::string, SwitchBlackbox::statistics>;

struct opt_t {
    bool save_stats = true;
    int num_workers = 4;
    std::string bin_filename = "";
    std::string human_readable_filename = "";
    std::string stats_filename = "";

    uint8_t N = 5; // Switches
    uint8_t M = 9; // Outputs
    uint8_t V = 15; // Vertices
} opt;

int main() {
    // single worker test
   
    uint8_t N = 5; // Switches
    uint8_t M = 9; // Outputs
    uint8_t V = 15; // Vertices
    SwitchBlackbox sbb(N, M, V);
    do
    {
        sbb.generate();
    } while (sbb.unique_vertices_no_less_than_m());
    sbb.best_choice_of_m_vertices();
     
}
#if 0
int main2() {
    const opt_t opt;
    ThreadSafeQueue<data_t> queue;
    std::atomic<bool> workers_running{true};

    // 1. Launch the Writer (Consumer) Thread
    std::jthread writer_thread([&queue, &opt]() {
        std::ofstream bf(opt.bin_filename);
        if (!bf.is_open()) {
            std::cerr << "Error: Could not open bin file.\n";
            return;
        }
        std::ofstream hf(opt.human_readable_filename);
        if (!hf.is_open()) {
            std::cerr << "Error: Could not open human readable data file.\n";
            return;
        }
        std::ofstream sf(opt.stats_filename);
        if (!sf.is_open()) {
            std::cerr << "Error: Could not open statistics file.\n";
            return;
        }

        while (true) {
            auto [serialized_data, readable_data, stats] = queue.pop_blocking();

            // Sentinel check ("Poison Pill"): Stop signal received
            if (serialized_data.size() == 0) {
                break;
            }

        }
        
        std::cout << "Writer thread: Queue drained and file safely closed.\n";
    });

    // 2. Launch N Worker (Producer) Threads
    std::vector<std::jthread> worker_threads;
    worker_threads.reserve(opt.num_workers);

    for (int i = 0; i < opt.num_workers; ++i) {
        worker_threads.emplace_back([&queue, &workers_running, &opt](int id) {
            int counter = 0;
                SwitchBlackbox generator(opt.N, opt.M, opt.V);
            while (workers_running.load(std::memory_order_relaxed)) {
                // Simulate data generation
                do {
                    generator.generate();
                } while (!generator.check());


                queue.push(data_t{id, ++counter});
                
                // Slow down workers slightly to prevent instant memory bloating
                std::this_thread::sleep_for(std::chrono::milliseconds(50));
            }
            std::cout << "Worker " << id << " has finished producing.\n";
        }, i);
    }

    // 3. Main thread runs the application pipeline duration
    std::cout << "Application running. Workers generating data...\n";
    std::this_thread::sleep_for(std::chrono::seconds(3)); 

    // 4. Orderly Shutdown Sequence
    std::cout << "\nInitiating shutdown sequence...\n";
    
    // Step A: Tell workers to break their loops
    workers_running.store(false, std::memory_order_relaxed);

    // Step B: Wait for all workers to join (guarantees no more real data is added)
    worker_threads.clear(); 
    std::cout << "All workers joined.\n";

    // Step C: Push the sentinel value to unlock and terminate the writer thread
    queue.push(data_t{{}, "", {}});

    // Step D: The writer_thread will automatically join here as it falls out of scope
    return 0;
}
#endif
