// draft is generated by Gemini
#include <iostream>
#include <vector>
#include <numeric>
#include <random>
#include <algorithm>
#include <cmath>
#include <set>
#include <map>
#include <string>
#include <array>
#include <functional>
#include <iostream>
#include <fstream>
#include <thread>
#include <atomic>
#include <chrono>

#include "DSU_uint8.hpp"
#include "SwitchBlackbox.hpp"
#include "ThreadSafeQueue.hpp"

#define DEBUG 1

// define a macro to run function only in debug mode
#define DEBUG_RUN(func) do { if (DEBUG) { func; } } while(0)

void debug_print(const std::string& msg) {
    if (DEBUG) {
        std::cout << msg << std::endl;
    }
}

struct opt_t {
    bool save_stats = true;
    int num_workers = 4;
    std::string bin_filename = "";
    std::string human_readable_filename = "";
    std::string stats_filename = "";

    uint8_t N = 5; // Switches
    uint8_t M = 9; // Outputs
    uint8_t V = 15; // Vertices
} opt;

int main() {
    // single worker test
   
    uint8_t N = 5; // Switches
    uint8_t M = 8; // Outputs
    uint8_t V = 15; // Vertices
    SwitchBlackbox sbb(N, M, V);
    int cnt = 0;
    uint32_t max_dist_adj = 0;
    uint32_t max_dist_2 = 0;
    int min_stdev = INT_MAX;
    int max_n1s = 0;
    while (cnt < 20000) {
        SwitchBlackbox::Statistics s;
        do
        {
            sbb.generate();
            s = sbb.basic_stats();
        } while (s.max_reachable_n < M);
        int n_unique = sbb.best_choice_of_m_vertices();
        if (n_unique == 1 << N) {
            auto dist_1 = sbb.sum_reachable_distance_for_adjacent_bitmasks(1, V);
            auto dist_2 = sbb.sum_reachable_distance_for_adjacent_bitmasks(2, V);
            auto n1s = sbb.n_1s();
            auto stdev = sbb.stdev();

            bool good = false;
            if (dist_2 > max_dist_2) {
                good = true;
                max_dist_2 = dist_2;
            }
            if (dist_1 > max_dist_adj) {
                good = true;
                max_dist_adj = dist_1;
            }
            if (n1s > max_n1s) {
                good = true; 
                max_n1s = n1s;
            }
            if (stdev < min_stdev || stdev == 0) {
                good = true;
                min_stdev = stdev;
            }

            if (good) {
                std::string config = sbb.get_readable_config();
                std::cout << "Unique config: " << n_unique << ", config: " << config;
                std::cout << "distance 1: " << dist_1 << ", distance 2: " << dist_2 << ", n1s:" << n1s << ", stdev: " << stdev << std::endl;

                // test load function
                sbb.generate(sbb.get_readable_config());
                if (config != sbb.get_readable_config()) {
                    std::cerr << "error!" << std::endl;
                }
            }
            
            ++cnt;
        }
    }
    return 0;
}
